### ISSUE TITLE
Build fails - ./configure not generated?

### ISSUE THREAD

**Issue by Armael** [michipili/rashell#13]
When trying to install rashell via opam, on my computer the compilation fails at `./configure --prefix /home/armael/4.02.3`.

It looks like that indeed, the `./configure` script is not shipped in the archive. Is a call to `autoconf` missing in the build instructions, in the `opam` file?

**Comment by Armael** [comment]
Would #14 be the correct way to fix that?

**Comment by michipili** [comment]
IMO the right way to handle the configure script is to not have it in the repository (it can be generated) and to have it in the distribution tarballs (it has to be canonical).

Which version did you try to build? In the latest release (v0.2.1) the configure script is in the archive:

```console
% tar tzf rashell-0.2.1.tar.gz | grep configure
rashell-0.2.1/configure
rashell-0.2.1/configure.ac
```

If you *pin* the repository, you will need to generate the configure file manually, this is documented in the README file (on master).

**Comment by Armael** [comment]
Ah, my bad. I only tried installing from opam (which only has v0.2.0); and then tried to opam pin using directly the http url of the repository, which I understand is not supposed to work.

**Comment by michipili** [comment]
No problem! :) And thank you for preparing a patch, even if it does not turn out to be used! :)

I think there is no action to be taken here, if you also think so, you are welcome to close this issue! :)

**Comment by Armael** [comment]
Alright. Will the v0.2.1 be released in opam?

**Comment by michipili** [comment]
It will, we however have more and more problems with the CI suite in opam-repository, so that my PRs are a bit lagging.

**Comment by Armael** [comment]
Ok, no problem.
