### ISSUE TITLE
Missing "autoconf" when building the project with Opam

### ISSUE THREAD

**Issue by Engil** [michipili/rashell#2]
Hi,
I tried building the project as explained in the README, using `opam pin add rashell .`, but it seems that there is a missing `configure` file, causing the build to abort.
I fixed it by either adding ['autoconf'] in `opam/opam` or by running `autoconf` myself before pinning it with Opam.
After that the installation went great and everything is working. :)

**Comment by michipili** [comment]
Thank you for reporting!

This is my intent that the `./configure` script is not part of the source code (but part of the distribution tarballs), so I will update the `opam` script to optionally rebuild it if not available.

**Comment by Engil** [comment]
I understand. :)
I also noticed the issue in gasoline, lemonade and dockertk, fixed it in the same way.
Thank you for your reply!

**Comment by michipili** [comment]
You're welcome, your feedback is much appreciated!  Good luck with docker_gc :)

**Comment by michipili** [comment]
Fixed! ac7e946
