### ISSUE TITLE
Feature request: support for volumes in Rashell_Docker.run*

### ISSUE THREAD

**Issue by mfp** [michipili/rashell#4]
Ideally, all this functionality should be exposed:

1. storage/source
  * plain volumes (storage managed by Docker daemon)
  * host directories mounted as data volumes
  * host files mounted as data volumes
  * importing volumes from other containers (`--volumes-from`)
2. mount options (read-only, ...)

**Comment by michipili** [comment]
This is a great idea and improving volumes support would be useful to implement https://github.com/michipili/dockertk/issues/3.

**Comment by mfp** [comment]
Gave it a hand in #10. Supports all the functionality listed above. The interface is also meant to be forward-compatible with future Docker volume mount options.

**Comment by michipili** [comment]
Thanks, I'll review it soon! :)

**Comment by michipili** [comment]
Thank you for the good work!
