### ISSUE TITLE
Listing docker images fails

### ISSUE THREAD

**Issue by michipili** [michipili/rashell#42]
Latest docker versions changed the “virtual size” to “size” to label the corresponding output column in `docker images` which breaks listing docker images.

Does someone see any value in keeping compatibility with obsolete versions of docker, or can we just move on?

@mfp, @Armael what is the oldest version of docker you use rashell with?  I would add a compatibility note in the docs and a check in the configure script.

**Comment by Armael** [comment]
I don't use docker, so as far as I'm concerned, you don't need to preserve retrocompatibility.

**Comment by mfp** [comment]
On Tue, Oct 18, 2016 at 07:31:21AM -0700, Michael Grünewald wrote:

> Latest docker versions changed the “virtual size” to “size” to label the corresponding output column in `docker images` which breaks listing docker images.
> 
> Does someone see any value in keeping compatibility with obsolete versions of docker, or can we just move on?

I happen to have a patch to support both outputs (and thus both old and newer
versions of Docker). I've just rebased that branch atop master and pushed it
to

```
https://github.com/mfp/rashell/tree/custom-rebased
```

I'm submitting a PR to serve as a reminder, but feel free to cherry-pick as
needed (creating 9 separate PRs felt quite overkill...)

## 

Mauricio Fernández

**Comment by foretspaisibles** [comment]
Fixed in f55cbca8315a94bfefa1e6f8c76ca9547cb82a7c, thank you @mfp!
