### ISSUE TITLE
Fix build matrix for CI

### ISSUE THREAD

**Issue by michipili** [michipili/rashell#7]
We now depend on `lwt.ppx` which breaks builds on pre-ppx versions of OCaml. Maybe we could also back port the ppx lwt-ish constructs.

**Comment by rgrinberg** [comment]
Is it possible to just refrain from using lwt.ppx until pre-ppx OCaml becomes more obsolete?

**Comment by michipili** [comment]
It is definitely possible! I think there are only very few `lwt.pxx` constructs in the code, and the equivalence is trivial anyway.

**Comment by michipili** [comment]
6f01823d1470d10b6c23150ce9f9d492bcdf537d
